package com.softdesign.devintensive.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softdesign.devintensive.data.storage.models.Repositiry;
import com.softdesign.devintensive.data.storage.models.User;

import com.softdesign.devintensive.data.storage.models.RepositiryDao;
import com.softdesign.devintensive.data.storage.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repositiryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RepositiryDao repositiryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repositiryDaoConfig = daoConfigMap.get(RepositiryDao.class).clone();
        repositiryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repositiryDao = new RepositiryDao(repositiryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Repositiry.class, repositiryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        repositiryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public RepositiryDao getRepositiryDao() {
        return repositiryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
